# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Myself' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'FMDB', '~> 2.6.2'
   pod 'SDWebImage', '~> 4.0.0'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Shimmer', '~> 1.0.2'

  # Pods for Myself

  target 'MyselfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyselfUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
